---
date: "Dec 17, 2019"
output:
  html_document:
    css: grapacciuolo-resume-theme.css
---

Giovanni Rapacciuolo, Ph.D. 
==========================

--------------------------------------------------------     --------------------------------
[Institute for Biodiversity Science & Sustainability][1]         **email** giorapac@gmail.com
California Academy of Sciences                                    **phone** +1 (510) 610-5646
San Francisco                                                 **www** [giorapacciuolo.com][2]
California 94118, USA                                            **twitter** [\@giorapac][56]
--------------------------------------------------------     --------------------------------

KEY EXPERTISE
-------------

Biodiversity and Global Change

:   Modeling of past and future impacts of environmental change on the distribution of species and ecosystems.

:   Geospatial analyses and GIS.

:   Systematic conservation planning.

Data Science

:   Synthesis, management, analysis of big datasets.

:   Interactive web-based visualizations and information sharing.

:   Open and reproducible science workflows.

Leadership and Management

:   Expertise at the interface between biodiversity modeling and conservation practice.

:   Leadership of multi-disciplinary teams and diverse stakeholder groups.

:   Excellent written and oral communication and knowledge transfer skills.

EDUCATION
---------
 
2009 - 2013

:   **Ph.D., Biodiversity and Global Change. Imperial College London, UK**      
    
    Title: ["Predicting species range shifts under global change: when can species distribution models be useful?"][31].    
    
    *  Model distribution responses of British plants, birds and butterflies to recent environmental changes.
    *  Develop methods to test the transferability of species distribution models in space and time.
    
    Advisors: Prof Andy Purvis (Imperial College London), Dr David Roy (Centre for Ecology and Hydrology)
        
2005 - 2009

:   **MSci (undergraduate degree), Biology, 1^st^ class honors. Imperial College London, UK**
 
PROFESSIONAL EXPERIENCE
-----------------------
2018 - present
:   **Research Scientist. California Academy of Sciences, CA, USA**
    
    *  Build capacity to use community-based science efforts to inform management of coastal biodiversity and Marine Protected Areas in California.
    *  Lead the preparation of reports to California Fish and Wildlife and California Ocean Protection Council.
    *  Organize, host and run meetings with scientists, conservation practitioners, policymakers, and members of the public to discuss research findings and explore recommendations.

    Funding: [California Ocean Protection Council][52].  
    
2017 - 2018 
:   **Postdoctoral Scholar. University of California Merced, CA, USA**
    
    *  Model the drivers of ecological community structure and dynamics in Palau marine lake ecosystems
    *  Integrate modern ecological survey data with paleoecological data
    
    Advisors: Prof Michael Dawson, Prof Jessica Blois. Funding: [NSF Dimensions of Biodiversity Grant][30].
    
2015 -  2017 
:   **Biodiversity Postdoctoral Associate. NatureServe, VA, USA** 
    
    *  Model the drivers of species, functional and phylogenetic biodiversity across terrestrial vertebrates.
    *  Analyze the relationship among biodiversity dimensions in spatial conservation planning.
    *  Project the future impacts of species extinctions on terrestrial vertebrate biodiversity.
    
    Advisors: Dr Bruce Young, Prof Catherine Graham. Funding: [NSF Dimensions of Biodiversity Grant][14].


<p style="page-break-before: always">
<br>
<br>


2013 - 2015 
:   **Postdoctoral Scholar. University of California Berkeley, CA, USA**      
    
    *  Model the responses of California plants, vertebrates and invertebrates to 20th century climate change.
    *  Collaborate on building an online tool ([https://holos.berkeley.edu/][15]) integrating many spatial and temporal biodiversity data sources to advance understanding of biotic responses to global change.
    
    Advisors: Prof Rosemary Gillespie, Prof Charles Marshall. Funding: [Berkeley in Global Change Biology][39].

GRANTS AND AWARDS
------
2019 — $1,100

:   [**Ecography Award for Excellence in Ecology and Evolution, Winner**][50]. Nordic Society Oikos, SWE.

2015 — $5,000

:   [**Socio-environmental Immersion Fellowship**][18]. National Socio-Environmental Synthesis Center, MY, USA.

2013 — $100,000

:   [**Postdoctoral Scholarship**][21]. Berkeley Initiative in Global Change Biology, CA, USA.      
    
2009 — $50,000

:   [**Climate Change Research Scholarship**][20]. Old Mutual plc, UK.      

PUBLICATIONS                                                        
------------   

### Peer-reviewed &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; [Google Scholar profile][9] | [Altmetrics data][8]

Submitted

:     Santini L, Antão L, Jung M, Benítez-López A, Rapacciuolo G, Di Marco M, Jones F, Haghkerdar J, González-Suárez M. The interface between Macroecology and Conservation: existing links and untapped opportunities. *Biological Conservation*.

2020

:     Zurell D [and 22 others, including **Rapacciuolo G**] (2020). A standard protocol for reporting species distribution models. *Ecography*. [Find full text][54].

2019

:     **Rapacciuolo G**, Rominger AJ, Morueta-Holme N, Blois JL (2019). Editorial: Ecological non-equilibrium in the Anthropocene. *Frontiers in Ecology and Evolution* **7**:428. [Find full text][53].

:     **Rapacciuolo G**, Beman JM, Schiebelhut LM, Dawson MN (2019). Microbes and macro-invertebrates show parallel beta-diversity but contrasting alpha-diversity patterns in a marine natural experiment. *Proceedings of the Royal Society B* **286**. [Find full text][51].

:     **Rapacciuolo G** & Blois J (2019) Understanding ecological change across large spatial, temporal and taxonomic scales: integrating data and methods in light of theory. *Ecography* **42**: 1247-1266. [Find full text][46]. **This publication was awarded the [Ecography Award for Excellence in Ecology and Evolution][50]**. 

:     Bouchet PJ [and 28 others, including **Rapacciuolo G**] (2019). Better Model Transfers Require Knowledge of Mechanisms. *Trends in Ecology and Evolution* **34**: 489-490. [Find full text][45]. 

:     Radeloff VC [and 17 others, including **Rapacciuolo G**] (2019). The Dynamic Habitat Indices (DHIs) from MODIS and global biodiversity. *Remote Sensing of Environment* **222**: 204-214. [Find full text][44].

:     **Rapacciuolo G**, Graham CH, Marin, J, Behm JE, Costa GC, Hedges SB, Helmus MR, Radeloff VC, Young BE, Brooks TM (2019). Species diversity as a surrogate for the conservation of phylogenetic and functional diversity in terrestrial vertebrates across the Americas. *Nature Ecology & Evolution* **3**: 53-61. [Find full text][43].

:     **Rapacciuolo G**. (2019). Strengthening the contribution of macroecological models to conservation practice. Invited contribution for the Macroecology 30th Anniversary Issue at *Global Ecology and Biogeography* **28**: 54-60. [Find full text][42].


<p style="page-break-before: always">
<br>
<br>


2018

:     Yates KL [and 49 others, including **Rapacciuolo G**] (2018). Outstanding challenges in the transferability of ecological models. *Trends in Ecology and Evolution* **33**: 790-802. [Find full text][41].

:     Marin J, **Rapacciuolo G**, Costa GC, Graham CH, Brooks TM, Young BE, Radeloff VC, Behm JE, Helmus MR, Hedges SB (2018). Evolutionary time drives global tetrapod diversity. *Proc. Roy. Soc. B* **285**. [Find full text][40].

2017

:     **Rapacciuolo G**, Ball-Damerow JE, Zeilinger A, Resh VH (2017). Detecting long-term occupancy changes in Californian odonates from natural history and citizen science records. *Biodiversity and Conservation* **26**: 2933-2949. [Find full text][33].

:     **Rapacciuolo G**, Marin J, Costa GC, Helmus MR, Behm JE, Brooks TM, Hedges SB, Radeloff VC, Young BE, Graham CH (2017). The signature of human pressure history on the biogeography of body mass in tetrapods. *Global Ecology and Biogeography* **26**: 1022-1034. [Find full text][32].

:     Zeilinger A, **Rapacciuolo G**, Turek D, Oboyski P, Almeida R, Roderick G (2017). Museum specimen data reveal emergence of a plant disease may be linked to increases in the insect vector population. *Ecological Applications* **27**: 1827-1837. [Find full text][29].

:     Young BE, Auer S, Ormes M, **Rapacciuolo G**, Schweitzer D, Sears N (2017). Are pollinating hawk moths declining in the Northeastern United States? An analysis of collection records. *PLoS ONE* **12**: e0185683. [Find full text][36].

2016

:     Fiorella KJ, **Rapacciuolo G**, Trisos C. (2016). Species loss: learn from health metrics. *Nature (Correspondence)* **538**: 371. [Find full text][17].

:     Kelly M, Easterday K, **Rapacciuolo G**, Koo MS, McIntyre P, Thorne J. (2016). Rescuing and sharing historical vegetation data for ecological analysis: The California Vegetation Type Mapping project. *Biodiversity Data Journal* **11**: 40 - 62. [Find full text][16].  

2015

:     Pearse WD, Chase MW, Crawley MJ, Dolphin K, Fay MF, Joseph JA, Powney G, Preston CD, **Rapacciuolo G**, Roy DB, and Purvis A. (2015). Beyond the EDGE with EDAM: prioritising British plant species according to evolutionary distinctiveness, and accuracy and magnitude of decline. *PLoS One* **10**: e0126524. [Find full text][11].   

2014

:     **Rapacciuolo G**, Maher S, Schneider AC, Hammond TT, Jabis MD, Walsh WE, Iknayan KJ, Walden GK, Oldfather MF, Ackerly DD, Beissinger SR (2014). 
Beyond a warming fingerprint: individualistic biogeographic responses to heterogeneous climate change in California. *Global Change Biology* **20**: 2841 - 2855. [Find full text][3].

:     **Rapacciuolo G**, Roy DB, Gillings S, Purvis A (2014). 
Temporal validation plots: quantifying how well species distribution models predict species' range 
changes over time. *Methods in Ecology and Evolution* **5**: 407 - 420. [Find full text][4].

:     Powney GD, **Rapacciuolo G**, Preston CD, Purvis A, Roy DB (2014). 
A phylogenetically-informed trait-based analysis of range change in the vascular plant flora of 
Britain. *Biodiversity and Conservation* 23: 171 - 185. [Find full text][5].  

2012

:     **Rapacciuolo G**, Roy DB, Gillings S, Fox R, Walker K, Purvis A (2012). 
Climatic associations of British species distributions show good transferability in time but low 
predictive accuracy for range change. *PLoS One* **7**: e40212. [Find full text][6].

:     Oliver TH, Gillings S, Girardello M, **Rapacciuolo G**, Brereton TM, Siriwardena GM, Roy DB, Pywell R, Fuller RJ (2012). Population density but not stability can be predicted from species distribution models. *Journal of Applied Ecology* **49**: 581 - 590. [Find full text][7].


### Other publications ###

2020

:     Rapacciuolo G, Young A, Johnson R (2020). Monitoring California’s Coastal Biodiversity with Crowd-Sourced Citizen Science. *California Academy of Sciences, CA*, *California Ocean Protection Council, CA*, and *California Department of Fish and Wildlife, CA*. p. 38.[Find full text][55].

<p style="page-break-before: always">
<br>
<br>

2018

:     Rapacciuolo G (2018). Knowledge of species diversity may be sufficient to preserve other dimensions of biodiversity. *Nature Ecology & Evolution Community Blog*. [Find full text][58].

:     Rapacciuolo G (2018). It’s time to strengthen the macroecology–conservation practice interface (commentary). *Mongabay*. [Find full text][57].

TECHNICAL SKILLS
----------------

Biodiversity Modeling

:   Expertise in species distribution and occupancy modeling using Generalized Linear, Machine Learning, and Hierarchical Bayesian models.

:   Expertise in modeling spatial and temporal variation in of species, functional and phylogenetic diversity of ecological communities. 

:   Expertise in geospatial analyses and Geographic Information Systems (GIS) using R, ArcGIS and ArcPy.

:   Expertise in systematic spatial conservation planning using Zonation.

Programming and Data Science

:   Expertise in R programming and statistical environment for integration, manipulation and analysis of big data.

:   Expertise in data visualization and sharing using ggplot2, R Markdown, R Shiny, HTML, CSS.

:   Expertise in web-based interactive mapping and dashboard applications using leaflet, D3, plotly with R Shiny.

:   Expertise in in reproducible workflows, code version control and management using Git and GitHub.

:   Working knowledge of Python, SQL and JavaScript.

Languages

:   Trilingual: English (native), French (native), Italian (native).

INVITED TALKS
-------------
3 Aug 2020

:   **Ecological Society of America 2020 Annual Meeting, Virtual.**

    "Realizing the potential of big unstructured opportunistic data sources to detect changes in biodiversity".

28 Feb 2020

:   **University of California Berkeley, Berkeley, CA, USA.**

    "Detecting biodiversity change from unstructured citizen science data to inform coastal management". 
    
05 Feb 2020

:   **Sonoma State University, Santa Rosa, CA, USA.**

    "Detecting biodiversity change from unstructured citizen science data to inform coastal management". 

12 Nov 2019

:   **San Francisco State University, San Francisco, CA, USA.**

    "Detecting biodiversity change from unstructured citizen science data". 
    
22 Mar 2018

:   **University of California Berkeley, Berkeley, CA, USA.**

    "Dimensions of terrestrial vertebrate biodiversity: key drivers and opportunities for conservation". 

21 Apr 2017

:   **American Museum of Natural History, New York City, NY, USA.**

    "The consequences of species loss for terrestrial vertebrate biodiversity". 

24 Jan 2017

:   **University of California, Los Angeles, Los Angeles, CA, USA.**

    "Improving climate change vulnerability assessments using data on functional traits and historical distributions".

24 Apr 2014

:   **[Australian National University][27], Canberra, AU.**

    "Using historic data sources to calibrate and validate models of species' range dynamics".

21 Sep 2012

:   **[Botanical Society of the British Isles][28], Edinburgh, UK.**

    "Can we predict recently-observed changes in the British Flora?".

<p style="page-break-before: always">
<br>
<br>

CONFERENCE PRESENTATIONS
------------------------

### Talks ###

Jun 2020

:   "Increasing the usefulness of crowd-sourced citizen science data to monitor and understand biodiversity". Digital Data in Biodiversity Research Conference, Virtual.

Feb 2020

:   "Monitoring Marine Protected Areas using Citizen Science". AGU Ocean Sciences 2020, San Diego, CA, USA.

Dec 2019

:   "Monitoring Marine Protected Areas using Citizen Science". AGU 2020 Fall Meeting, San Francisco, CA, USA.


Apr 2019

:   "Monitoring Marine Protected Areas using Citizen Science". 5th Ocean Climate Summit, San Francisco, CA, USA.

Jan 2019

:   "Are there universal biodiversity rules? Insights from a marine natural experimental system". International Biogeography Society Biennial Meeting, Malaga, ES.

Jun 2018

:   "We have all the data, now what? The importance of planning for biodiversity data integration". Digital Data in Biodiversity Research Conference, Berkeley, CA, USA.

Sep 2011 - Talk

:   "Species distribution models fail to predict observed range shifts of British species from climate". Spatial Ecology and Conservation Conference, Birmingham, UK.

### Posters ###

Jan 2017 - Poster

:    "A signature of human pressure amid ecological constraints on the distribution of body mass in tetrapods". International Biogeography Society Meeting, Tucson, AZ, USA.

Apr 2014 - Poster

:    "Rescuing and integrating data in the face of global change". Understanding Biodiversity Dynamics Symposium, Canberra, AU.

TEACHING
--------
### Guest lecturer ###

2017 

:   "The Nature of Communities". Fundamentals of Ecology. University of California, Merced, CA, USA.

:   "Change in Communities". Fundamentals of Ecology. University of California, Merced, CA, USA.

### Teaching assistant ###

2011, 2012

:   Computing and Biodiversity courses. MS, Ecology, Evolution and Conservation, Imperial College London, UK. 
    
2010, 2011    
    
:   Statistics and Computing courses. years 1-3, BS, Biology, Imperial College London, UK.

### Graduate supervisor ###

2011    
    
:   Emma Sheard. MS, Ecology, Evolution and Conservation, Imperial College London, UK.

    Thesis title: "Can biotic interactions be used to explain the distribution of monophagous moths in Britain?".

### Undergraduate supervisor ###

2017, 2018

:   Carolina Karuppiah. BS, Psychology, University of California, Merced, CA, USA.

:   Zachary Malone. BS, Earth System Science, University of California, Merced, CA, USA.

2013

:   Arif Ali. BS, Computer Science, University of California, Berkeley, CA, USA.

### Co-instructor ###

2013, 2014

:   [Species Distribution Modeling workshop][26]. University of California, Berkeley, CA, USA.
    
2010, 2011    
    
:   Generalised Linear Modeling in R course. Imperial College London, UK.

<p style="page-break-before: always">
<br>
<br>

SERVICE AND OUTREACH
-----------------
### Editor ###

2017 - 2019

:   Guest Associate Editor for [Frontiers in Ecology and Evolution][35], Biogeography and Macroecology section.

:   Editor of topic ["Ecological non-equilibrium in the Anthropocene"][37] in Frontiers in Ecology and Evolution.

### Reviewer ###

Publications 

:   Reviewed for *Nature Communications*, *Trends in Ecology and Evolution*, *Biology Letters*, *Global Change Biology*, *Global Ecology and Biogeography*, *Ecography*, *Methods in Ecology and Evolution*, *Diversity and Distributions*, *Journal of Biogeography*, *Animal Conservation*, *Climate Risk Management*, *Climatic Change*, *Ecology and Evolution*, *IBIS*, *PLoS One*. [Publons profile][10].

Adaptation plans

:   ["Silicon Valley 2.0"][19]. Climate change adaptation assessment. Santa Clara Office of Sustainability, San Francisco, CA, USA. Sep 2014.

Grants

:   Reviewed for *National Science Foundation*. Nov 2015.

Software

:   "HYKL". Bayesian species distribution modeling. Microsoft Research, Cambridge, UK. Jun 2012.

### Organizer ###

Seminars

:   "Biotic responses to climate change in California". University of California, Berkeley, CA, USA. Apr-Dec 2013.

Meetings 

:   "Monitoring California's Coastal Biodiversity with Citizen Science" Stakeholder Webinar. California Academy of Sciences, San Francisco, CA. May 2020.

:   "Monitoring MPAs with Citizen Science" Stakeholder Meeting. California Academy of Sciences, San Francisco, CA. Jun 2019.

:   "Bay Area Biodiversity Modeling Working Group". California Academy of Sciences, San Francisco, CA. Mar 2019.

###  Developer  ###

Software

:   Published source code associated with a number of projects on [GitHub][38].

Web tools

:   Creator and developer of [http://calcoast.dob.bio][55]

:   Collaborated on [https://holos.berkeley.edu/][15].

:   Developed personal research website: [http://giorapacciuolo.com][2].

### Media coverage ###

2020

:   [Visits turned virtual: Building California's coastal observatory][59], California Academy of Sciences, CA, USA.

2019

:   [Biodiversity Study Indicates Large and Small Organisms React Similarly to Environment][61], Newsroom, UC Merced, CA, USA.

:   [City Nature Challenge segment, from minute 11:00][60], Inside Science, BBC Radio 4, UK. 

REFERENCES
----------

**Prof Rosemary Gillespie** | gillespie@berkeley.edu. Professor, University of California Berkeley, CA, USA. 
    
**Prof Andy Purvis** | andy.purvis@nhm.ac.uk. Research Leader, Natural History Museum, London, UK.

**Dr Rebecca Johnson** | rjohnson@calacademy.org, Co-Director Citizen Science, California Academy of Sciences, USA.

**Prof Jessica Blois** | jblois@ucmerced.edu, Associate Professor, University of California Merced, CA, USA.

**Dr Thomas Brooks** | thomas.brooks@iucn.org. Head, Science and Knowledge, IUCN, CH.

**Dr Catherine Graham** | catherine.graham@wsl.ch. Senior Scientist, Swiss Federal Research Institute, CH.

[1]:https://www.calacademy.org/scientists
[2]:http://giorapacciuolo.com
[3]:http://onlinelibrary.wiley.com/doi/10.1111/gcb.12638/abstract
[4]:http://onlinelibrary.wiley.com/doi/10.1111/2041-210X.12181/abstract
[5]:http://link.springer.com/article/10.1007/s10531-013-0590-5
[6]:http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0040212
[7]:http://onlinelibrary.wiley.com/doi/10.1111/j.1365-2664.2012.02138.x/full
[8]:http://giorapacciuolo.com/publication
[9]:https://scholar.google.com/citations?user=kLSLO8sAAAAJ&hl=en
[10]:https://publons.com/author/333635/giovanni-rapacciuolo#profile
[11]:http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0126524
[12]:https://github.com/giorap/tv-plots
[13]:https://github.com/giorap/nodiv
[14]:http://www.nsf.gov/awardsearch/showAward?AWD_ID=1136586
[15]:https://holos.berkeley.edu/
[16]:https://journals.ku.edu/index.php/jbi/article/view/5886/5871
[17]:http://www.nature.com/nature/journal/v538/n7625/full/538317d.html
[18]:http://www.sesync.org/immersion-program-participants-2015-2016
[19]:https://www.sccgov.org/sites/osp/Documents/SV2/1_150803_Final%20Guidebook_W_Appendices.pdf
[20]:http://www3.imperial.ac.uk/newsandeventspggrp/imperialcollege/naturalsciences/climatechange/newssummary/news_5-2-2010-11-55-34
[21]:http://globalchange.berkeley.edu/meet-scientist#Gio
[22]:http://biorxiv.org/content/early/2017/01/26/103507
[23]:https://swcarpentry.github.io/2014-03-17-ucb/
[24]:http://gif.berkeley.edu/support/workshop_descriptions.html#rs
[25]:http://dlab.berkeley.edu/training/working-geospatial-data-r
[26]:https://drive.google.com/file/d/0BxNqMqesSSmSNjNSRGpLYVoxRlE/view
[27]:http://cba.anu.edu.au/news-events/understanding-biodiversity-dynamics-using-diverse-data-sources/uses-and-misuses
[28]:https://aobblog.com/2012/07/conference-botanical-society-of-the-british-isles-20th-21st-september-2012/
[29]:http://onlinelibrary.wiley.com/doi/10.1002/eap.1569/full
[30]:https://www.nsf.gov/awardsearch/showAward?AWD_ID=1241255
[31]:http://ethos.bl.uk/OrderDetails.do?uin=uk.bl.ethos.631202
[32]:http://onlinelibrary.wiley.com/doi/10.1111/geb.12612/full
[33]:https://link.springer.com/article/10.1007/s10531-017-1399-4
[34]:https://www.sesync.org/project/propose-a-workshop/cross-disciplinary-statistical-applications-in-the-anthropocene
[35]:http://loop.frontiersin.org/people/465362/overview
[36]:http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0185683
[37]:https://www.frontiersin.org/research-topics/6796/ecological-non-equilibrium-in-the-anthropocene
[38]:https://github.com/giorap
[39]:https://globalchange.berkeley.edu/
[40]:http://rspb.royalsocietypublishing.org/content/285/1872/20172378
[41]:https://www.cell.com/trends/ecology-evolution/fulltext/S0169-5347(18)30181-2
[42]:https://onlinelibrary.wiley.com/doi/full/10.1111/geb.12848
[43]:https://www.nature.com/articles/s41559-018-0744-7
[44]:https://www.sciencedirect.com/science/article/pii/S0034425718305625
[45]:https://www.sciencedirect.com/science/article/pii/S0169534719301119
[46]:https://onlinelibrary.wiley.com/doi/full/10.1111/ecog.04616
[47]:https://grap.shinyapps.io/MPA_Biodiversity_Dashboard/
[48]:https://grap.shinyapps.io/MPA_iNat_Explorer/
[49]:https://grap.shinyapps.io/Snapshot_Exploratory_Tool/
[50]:https://twitter.com/EcographyJourna/status/1145673769765220354
[51]:https://royalsocietypublishing.org/doi/full/10.1098/rspb.2019.0999
[52]:http://www.opc.ca.gov/
[53]:https://www.frontiersin.org/articles/10.3389/fevo.2019.00428/full
[54]:https://onlinelibrary.wiley.com/doi/full/10.1111/ecog.04960
[55]:http://calcoast.dob.bio/monitoring-coastal-biodiversity-with-citizen-science-OPC-report-28May2020.pdf
[56]:https://twitter.com/giorapac
[57]:https://news.mongabay.com/2018/11/its-time-to-strengthen-the-macroecology-conservation-practice-interface-commentary/
[58]:https://natureecoevocommunity.nature.com/users/38305-giovanni-rapacciuolo/posts/41845-knowledge-of-species-diversity-may-be-sufficient-to-preserve-multiple-dimensions-of-biodiversity
[59]:https://www.youtube.com/watch?v=jVwHzXTii0M
[60]:https://www.bbc.co.uk/sounds/play/m0004cqh
[61]:https://news.ucmerced.edu/news/2019/biodiversity-study-indicates-large-and-small-organisms-react-similarly-environment
